config:
  backup: true
  create: true
  dotpath: dotfiles
  impignore:
  - '*.zwc'
  cmpignore:
  - '*.zwc'
  instignore:
  - '*/.git'
dotfiles:
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  d_asdf:
    src: config/asdf
    dst: ~/.config/asdf
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_swayidle:
    src: config/swayidle
    dst: ~/.config/swayidle
  d_npm:
    src: config/npm
    dst: ~/.config/npm
profiles:
  lambda.local:
    dotfiles:
    - d_kitty
    - f_zshenv
    - d_zsh
    - d_asdf
    - d_nvim
    - d_npm
  sigma:
    dotfiles:
    - d_kitty
    - f_zshenv
    - d_zsh
    - d_asdf
    - d_nvim
    - d_sway
    - d_swaylock
    - d_swayidle
    - d_npm
