config:
  backup: true
  create: true
  dotpath: dotfiles
  impignore:
  - '*.zwc'
  cmpignore:
  - '*.zwc'
  instignore:
  - '*/.git'
dotfiles:
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  d_asdf:
    src: config/asdf
    dst: ~/.config/asdf
profiles:
  lambda.local:
    dotfiles:
    - d_kitty
    - f_zshenv
    - d_zsh
    - d_asdf
