config:
  backup: true
  create: true
  dotpath: dotfiles
  impignore:
  - '*.zwc'
  - '*.so'
  - '*.revision'
  cmpignore:
  - '*.zwc'
  - '*.so'
  - '*.revision'
  - '*/.git'
  instignore:
  - '*/.git'
dotfiles:
  d_kitty:
    src: config/kitty
    dst: ~/.config/kitty
  f_zshenv:
    src: zshenv
    dst: ~/.zshenv
  d_zsh:
    src: config/zsh
    dst: ~/.config/zsh
  d_asdf:
    src: config/asdf
    dst: ~/.config/asdf
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  d_sway:
    src: config/sway
    dst: ~/.config/sway
  d_swaylock:
    src: config/swaylock
    dst: ~/.config/swaylock
  d_swayidle:
    src: config/swayidle
    dst: ~/.config/swayidle
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  f_tool-versions:
    src: tool-versions
    dst: ~/.tool-versions
profiles:
  lambda.local:
    dotfiles:
    - d_asdf
    - d_kitty
    - d_nvim
    - f_tool-versions
    - d_zsh
    - f_zshenv
  sigma:
    dotfiles:
    - d_asdf
    - d_kitty
    - d_nvim
    - d_ranger
    - d_sway
    - d_swayidle
    - d_swaylock
    - f_tool-versions
    - d_zsh
    - f_zshenv
