[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'morhetz/gruvbox'
