[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'dracula/vim'
name = 'dracula-vim'

[[plugins]]
repo = 'mhinz/vim-startify'
